### ISSUE TITLE
Resize Parcels Table Column Width to accommodate text

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#182]
### Describe the solution / feature you'd like

On the parcels table, the column size for 

Family
Postcode
Collection
Packing Date
Time 

are too wide, while 'Status' is too small. (Text is wrapping a lot)
Some tuning required of column width to make all row text readable with not too much blank space.

**Comment by kaydentsoftwire** [comment]
QA steps:
- navigate to parcels page
- [ ] Last Status column should be wider than the others and not overly wrapped 
- [x] When you make the browser shorter some columns should disappear but not overlap
- [x] When you expand the browser to a wider screen they should still remain stretched out across the page, with the contents of Last Status appearing on a single line
- [x] There are no other unusual visual/sizing issues with the column widths

**Comment by AmeliaIsCoding** [comment]
Well done, it looks really good and behaves well on changing the browser size. However, unfortunately there are a couple of long names and statuses that still wrap to the next row on my laptop screen, with the other columns still containing some blank space.
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/138508884/2e5fe5e9-562e-4b6e-8d4b-02661970a24e)
I would suggest you make the last status and name columns slightly wider still, and the other columns slightly narrower.
@kaydentsoftwire

**Comment by 8kristy** [comment]
It's still a bit narrow on smaller screens? 
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/5dee0040-016e-4565-bc07-4c88cba69a88)

Do we have separate styling for mobile and desktop? I think I'd aim for something like this 
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/ea2f166e-d219-484c-ac2d-9932c887ad32)

(or it doesn't look too bad I think even if we apply the same rules to both)
| Current styling | New styling |
|---|---|
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/f1644345-f9ff-43da-8c9a-a5ac37e8d1ab)| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/6210fc3f-f631-4447-ae2d-d9bf1470fc8f)|
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/cbd3a5d0-a55a-4299-9bc3-536b4f99c6e3)| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/42096009/8bd80e62-a084-4d4b-a9fe-0b9f585e8f75)|

**Comment by 8kristy** [comment]
Further notes on this: we may want to make Family, Postcode and Packing Date columns even smaller, so that they only need to fit the max number of characters required on one line (i.e. 13 for family ("Family of 10+"), 9 for postcode and 10 for date)
We need to give name and status as much space as possible

**Comment by kaydentsoftwire** [comment]
UPDATED QA STEPS:
  -  navigate to parcels page
   - [ ] Last Status column should be wider than the others and not overly wrapped
   - [ ] When you make the browser shorter some columns should disappear but not overlap
   - [ ] When the browser is smaller the columns should shrink so that the last status is not overly squash
   - [ ] When you expand the browser to a wider screen they should still remain reasonably stretched out across the page, with the contents of Last Status appearing on a single line, and Last Status and Full Name as the widest columns
   - [ ] There are no other unusual visual/sizing issues with the column widths

**Comment by Alex-Softwire** [comment]
QA:
✅ - Last status column is wider than the others and not overly wrapped. Generally looks nice and wraps in the right places.
✅ - Parcel page generally looks good on all browser sizes and zooms. Columns disappear and appear in sensible places, and there isn't too much overlap. 
Well done with that (the parcel page looks really readable, in lots of different shapes and sizes!)

❓ - The select columns to show button/dropdown doesn't allow you to add back columns that are removed with different sizes. It allows you to add columns that aren't usually there (voucher, phone number, created at), but does nothing when you select packing date on a small browser that has removed it already. 
❓ - Not necessarily part of this ticket, but the select columns dropdown allows you to deselect all, makes the whole table look a little funny.
❓ - What is the order that columns drop off and why? Packing date is pretty quick to go and that's the primary thing we sort by. 
❓ - The title of the packing slot column is sometimes a little close to the Last Status column, such that the sort by arrow sometimes overlaps with it. Not sure if that's too much of a problem.
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/107864173/7b78c9d8-1e0a-4073-b26a-d42a7d44686f)
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/107864173/717be2e3-9d74-432c-8ac7-6509c5f17dd5)

Great work with this though :)

**Comment by kaydentsoftwire** [comment]
Re the select column - how would you expect this to behave at a smaller size? I would perhaps expect to be able to swap one column out for another, or maybe you think you should be able to manually add columns back in even if it makes everything quite squashed?  The reason it doesn't affect it is because the column at a smaller size is still "there", it is just hidden in the styling.

Packing date, slot and postcode disappear at the same time. This is a pre-existing feature so I am not entirely sure on why these were chosen, I suppose the alternative is getting rid of family and keeping date? Perhaps the idea was that if you were just looking at today's list you don't need the date as much? 

Thanks for the spot on packing slot header.

**Comment by Alex-Softwire** [comment]
That makes sense as to why the select columns doesn't work for those columns but definitely feels wrong to me. A toggle that does nothing for some columns but something for others is a bit confusing - can imagine someone on a small device getting confused by this. I feel like the user should be able to add back the missing columns if they want to see the packing date, slot and postcode - screen size shouldn't reduce the amount of possible data. The table has a left right scroll right? Not sure how easy this would be but to make each column have a "minimum size" and if even with the minimum sizes, if the table is larger the than the screen then just to make it scrollable. I'm not sure if I like columns disappearing to begin with but if they are going to be I'd like it if they were disabled in the column select menu when they disappear if possible, so you can re-add them back if you need the info. Does that make sense / do you agree with this?

**Comment by kaydentsoftwire** [comment]
Note for the ticket: discussed elsewhere and agreed to make new tickets for the issues raised above.

**Comment by Alex-Softwire** [comment]
Happy with the above & to move this to done with the new tickets :)

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 3 months, presumed done
