### ISSUE TITLE
Calendar Page - Week View - Change Date format to day/month instead of month/day

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#232]
### Describe the solution / feature you'd like

On the Calendar page, on the Week and Day View, the format is in US Month/Day. Please can we change it to UK Day/Month
<img width="1543" alt="Screenshot 2024-04-04 at 17 08 53" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/f42f37c8-79fb-4adf-99c8-e310d1a4d99f">

**Comment by maxjohns0n** [comment]
### QA

- Navigate to calendar page
- Switch to "week" view
  - [ ] Dates are in UK format (day/month instead of month/day)
- Switch to "day" view
  - [ ] Title is in UK format (e.g. 2 May 2024 instead of May 2, 2024)
- For all three views (month/week/day):
  - [ ] Monday is the first day of the week
  - [ ] Times are displayed as 24h

**Comment by AmeliaIsCoding** [comment]
QA passed! Well done for your first merge! <3
