### ISSUE TITLE
Display 100 Parcels on Parcels page as Default

### ISSUE THREAD

**Issue by dan-langridge** [NorwoodAndBrixtonFoodbank/nbf-website#241]
### Describe the solution / feature you'd like

On the Parcels page, please can the page by default show 100 clients, with the option for the user to lower it if required. We rarely want to see less than the whole day so we can keep an eye on all things.

**Comment by rickaw** [comment]
## QA steps
- [ ] When you open the parcels page, the table has by default selected 100 as the number of rows per page (note that the current data only has around 30 parcels each day, but you can check that the 100 is selected)
- [ ] When you then expand the date range so that more than 100 parcels exist, you indeed see 100 parcels on the table

**Comment by minalui** [comment]
QA Passed

[x] When you open the parcels page, the table has by default selected 100 as the number of rows per page (note that the current data only has around 30 parcels each day, but you can check that the 100 is selected)
[x] When you then expand the date range so that more than 100 parcels exist, you indeed see 100 parcels on the table
